### PR TITLE
Toolretriever for Agent OpenAI broken

### PR DESCRIPTION
**Pull request by Wesselvdp**
Hi, I ran into some issues with the multi documents example. It seems like the toolRetriever for an OpenAI agent is broken. 

Since the constructor has a default value with `tools = []` on line 93, checking if tools are an array seems unnecessary. Additionally, the if block on line 112 was always true. This resulted in the `toolRetriever` never working. 

Also, are you hiring? 🚀

### CODE REVIEW

**Comment by marcusschiesser** [comment]
@Wesselvdp Thanks for your contribution - great catch!

@himself65 is currently improving the agent; I guess the `toolRetriever` also needs some re-work.

@Wesselvdp Please note that your current code breaks if you set `tools` to `undefined`, e.g.:
```
new OpenAIAgent({
    tools: undefined,
    toolRetriever: await objectIndex.asRetriever({}),
```

About getting hired: Sending PRs is the right step to get our attention. Please continue working on more complex examples. Having a look at open issues is a great start.

**Review by himself65 — COMMENTED** [review]
Could you provide some test example?

**Comment by Wesselvdp** [comment]
@marcusschiesser, thanks for the quick response. I don't see the tests failing with my code + undefined tools. All tests seem to pass with the following change to the [Agent runner test](https://github.com/run-llama/LlamaIndexTS/blob/728b35e774d0c2742dcf132e0e25cfc9863837a0/packages/core/tests/agent/runner/AgentRunner.test.ts#L22). Did I miss anything?

```ts
 agentRunner = new AgentRunner({
      agentWorker: new OpenAIAgentWorker({ tools: undefined }),
    });
```
While writing some tests for this PR, I realised changing the params signature [type here ](https://github.com/run-llama/LlamaIndexTS/blob/728b35e774d0c2742dcf132e0e25cfc9863837a0/packages/core/src/agent/openai/worker.ts#L69) might make sense.
```ts
type OpenAIAgentWorkerParams = {
  llm?: OpenAI;
  prefixMessages?: ChatMessage[];
  maxFunctionCalls?: number;
} & (
  | { toolRetriever?: ObjectRetriever; tools?: never }
  | { toolRetriever?: never; tools?: BaseTool[] }
);
```

Not allowing both `tools` and `toolRetriever` to coexist in the params represents the function downstream better since the constructor of the `OpenAIAgentWorker` class [will throw an error](https://github.com/run-llama/LlamaIndexTS/blob/728b35e774d0c2742dcf132e0e25cfc9863837a0/packages/core/src/agent/openai/worker.ts#L110-L111) if that's the case.


@himself65 , on it.

**Comment by Wesselvdp** [comment]
@himself65 

The code below is a simplified version of the [multi documents agents](https://github.com/run-llama/LlamaIndexTS/blob/main/examples/agent/multi_document_agent.ts). I've added some console logs for pointing out the problem. You'll need that extractwikipedia function from the original example too.

```typescript
import fs from "node:fs/promises";

import {
  Document,
  ObjectIndex,
  OpenAI,
  OpenAIAgent,
  QueryEngineTool,
  Settings,
  SimpleNodeParser,
  SimpleToolNodeMapping,
  SummaryIndex,
  VectorStoreIndex,
  storageContextFromDefaults,
} from "llamaindex";

import { extractWikipedia } from "./extractwikipedia";

const wikiTitles = ["Brazil"];
Settings.llm = new OpenAI({ model: "gpt-4" });

const storageContext = await storageContextFromDefaults({
  persistDir: "./storage",
});

async function main(
  question = "Tell me something about the brazilian economy"
) {
    await extractWikipedia(wikiTitles);
  const countryDocs: Record<string, Document> = {};

  for (const title of wikiTitles) {
    const path = `public/tmp_data/${title}.txt`;
    const text = await fs.readFile(path, "utf-8");
    const document = new Document({ text: text, id_: path });
    countryDocs[title] = document;
  }

  // TODO: fix any
  const documentAgents: any = {};
  const queryEngines: any = {};

  for (const title of wikiTitles) {
    console.log(`Processing ${title}`);

    const nodes = new SimpleNodeParser({
      chunkSize: 200,
      chunkOverlap: 20,
    }).getNodesFromDocuments([countryDocs[title]]);

    console.log(`Creating index for ${title}`);

    const vectorIndex = await VectorStoreIndex.init({
      storageContext,
      nodes,
      logProgress: true,
    });

    const summaryIndex = await SummaryIndex.init({
      nodes,
    });

    console.log(`Creating query engines for ${title}`);

    const vectorQueryEngine = summaryIndex.asQueryEngine();
    const summaryQueryEngine = summaryIndex.asQueryEngine();

    const queryEngineTools = [
      new QueryEngineTool({
        queryEngine: vectorQueryEngine,
        metadata: {
          name: "vector_tool",
          description: `Useful for questions related to specific aspects of ${title} (e.g. the history, arts and culture, sports, demographics, or more).`,
        },
      }),
      new QueryEngineTool({
        queryEngine: summaryQueryEngine,
        metadata: {
          name: "summary_tool",
          description: `Useful for any requests that require a holistic summary of EVERYTHING about ${title}. For questions about more specific sections, please use the vector_tool.`,
        },
      }),
    ];

    console.log(`Creating agents for ${title}`);

    const agent = new OpenAIAgent({
      tools: queryEngineTools,
      llm: new OpenAI({ model: "gpt-4" }),
    });

    documentAgents[title] = agent;
    queryEngines[title] = vectorIndex.asQueryEngine();
  }

  const allTools: QueryEngineTool[] = [];

  console.log(`Creating tools for all countries`);

  for (const title of wikiTitles) {
    const wikiSummary = `This content contains Wikipedia articles about ${title}. Use this tool if you want to answer any questions about ${title}`;

    console.log(`Creating tool for ${title}`);

    const docTool = new QueryEngineTool({
      queryEngine: documentAgents[title],
      metadata: {
        name: `tool_${title}`,
        description: wikiSummary,
      },
    });

    allTools.push(docTool);
  }

  console.log("creating tool mapping");

  const toolMapping = SimpleToolNodeMapping.fromObjects(allTools);

  const objectIndex = await ObjectIndex.fromObjects(
    allTools,
    toolMapping,
    VectorStoreIndex
  );

  const toolRetriever = await objectIndex.asRetriever({});

  // This is the function the agent is running under it's hood for retrieving the tool.
  // You'll see that calling the function here retrieves the tool just fine.
  const retrievedTool = await toolRetriever.retrieve(question);
  console.log({ retrievedTool });

  const topAgent = new OpenAIAgent({
    toolRetriever,
    llm: new OpenAI({ model: "gpt-4" }),
    prefixMessages: [
      {
        content:
          "You are an agent designed to answer queries about a set of given countries. Please always use the tools provided to answer a question. Do not rely on prior knowledge.",
        role: "system",
      },
    ],
  });

  const response = await topAgent.chat({
    message: question,
  });

  // In the response below you'll see "sources" and "nodes" are empty
  console.log({ response });
  return response;
}

export default main;

```

This screenshot shows the output of the logs: the difference between manually calling the retriever and letting the agent do the work:
image

**Comment by himself65** [comment]
> I don't see the tests failing with my code + undefined tools.

Test cases doesn't cover all cases, I will upload your example as a test case

**Comment by himself65** [comment]
LGTM but we need improve those agent code in the future

**Pull request merged**
