### PR TITLE
feat: build api reference pages for new documentation site

### PR DESCRIPTION
**Pull request by thucpn**

### CODE REVIEW

**Review by himself65 — DISMISSED** [review]
https://llamaindex-ts-doc-git-feat-migrate-legacy-docs.pr.staging.llamaindex.ai/docs/api/classes/AnthropicAgent

Content looks not right. missing CSS?

**Comment by marcusschiesser** [comment]
That's how the API now looks like:

image

**Review by marcusschiesser — APPROVED** [review]
@himself65 LGTM - please merge if ok

**Review by himself65 — APPROVED** [review]
Great

**Pull request merged**
