### PR TITLE
fix: replace instanceof check with `.type` check

### PR DESCRIPTION
**Pull request by himself65**
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/1179
Similar issue: https://github.com/yjs/yjs/issues/438

### CODE REVIEW

**Comment by parhammmm** [comment]
if anyone is using next.js and comes across this, adding the following to your `next.config.mjs` this will fix it:

`experimental: { serverComponentsExternalPackages: ["@llamaindex/env",...] },`

**Comment by himself65** [comment]
thanks for updating solution

**Comment by nick-solly** [comment]
> if anyone is using next.js and comes across:
> 
> `llamaindex was already imported. This breaks constructor checks and will lead to issues!`
> 
> Adding the following to your `next.config.mjs` this will fix it:
> 
> `experimental: { serverComponentsExternalPackages: ["@llamaindex/env",...] },`

Thanks @parhammmm - this was driving me insane!

**Comment by parhammmm** [comment]
@nick-solly 

No prob! glad it helped 👍🏼

**Pull request merged**
