### PR TITLE
Add support for AstraDB in the create-llama cli

### PR DESCRIPTION
**Pull request by erichare**
Python code only, no typescript at the moment

### CODE REVIEW

**Comment by EmanuelCampos** [comment]
@erichare some tests are broken, can you check that and make sure it's following what create-llama expects?

**Comment by erichare** [comment]
@EmanuelCampos what's interesting is from what i can tell, the tests are saying that an OpenAI Key is not being provided. i didnt think that anything i added specified something specific about OpenAI, like using it as the service context. So I can't quite make sense of this. Do you have any thoughts? I could be missing something completely.

**Comment by marcusschiesser** [comment]
@erichare, yes, the e2e tests are not running for outside contributors. The reason is that this could leak the OpenAI key from our CI pipeline. But no worries; we'll use this PR as a draft for adding AstraDB to create-llama. 
Thanks a lot for your contribution!

Next steps:
1. adding TS code for using AstraDB vector store
2. modifying create-llama to add AstraDB as an option

**Comment by marcusschiesser** [comment]
Will continue on this in https://github.com/run-llama/create-llama

**Comment by marcusschiesser** [comment]
Just merged this to `main` of  https://github.com/run-llama/create-llama - will be in the next release

**Pull request closed without merging**
