### PR TITLE
fix: update user agent in AssemblyAI

### PR DESCRIPTION
**Pull request by Swimburger**
- Update the AssemblyAI SDK to 4.6.0
- Add LlamaIndexTS to user agent which lets us attribute usage to LlamaIndexTS

### CODE REVIEW

**Comment by marcusschiesser** [comment]
@Swimburger thanks for the update! Can you have a look please as the lints and tests?

**Review by himself65 — CHANGES_REQUESTED** [review]
you might forgot to commit package.json

**Comment by Swimburger** [comment]
Hi folks, someone seems to already have updated the assemblyai package to 4.6.0, hence it's not included in this PR.
The linting and testing issues are coming from code that we haven't touched. Not sure what is causing the issues.

**Review by marcusschiesser — APPROVED** [review]

**Comment by marcusschiesser** [comment]
@himself65 LGTM now

**Review by himself65 — APPROVED** [review]
LGTM

**Comment by Swimburger** [comment]
Is this good to merge now? 🙇

**Pull request merged**
