### PR TITLE
feat: metadata filtering on simplevectorstore

### PR DESCRIPTION
**Pull request by swiecki**
a starting point for a potential implementation of metadata filtering on simple vector store

### CODE REVIEW

**Comment by swiecki** [comment]
I'm hoping someone can take this as a starting point and finish the implementation from here. Fair warning what is present here might be garbage relative to the standards you guys are looking for.

**Comment by marcusschiesser** [comment]
@swiecki, that already looks very good! Great job, thanks a lot. Can you add a unit test and a changeset (just call `pnpm changeset`) - then I would be happy to merge it

**Comment by EmanuelCampos** [comment]
bump @swiecki

**Comment by sirpy** [comment]
metadataDict is used, but its:
1. not defined
2. never filled with content

**Review by himself65 — COMMENTED** [review]
LGTM just need test cases and rebease

**Comment by marcusschiesser** [comment]
closing as metadatafilters are already implemented for SimpleVectorStore - for usage check https://github.com/run-llama/LlamaIndexTS/blob/main/examples/metadata-filter/simple.ts

**Pull request closed without merging**
