### PR TITLE
Add MongoReader [Needs merge]

### PR DESCRIPTION
**Pull request by kkang2097**
## Summary
We need a simple document reader to handle MongoDB documents. 
- wrote a small class that implements existing interfaces
    - package/core/src/readers/SimpleMongoReader.ts
- wrote a mini-app  to demonstrate how to integrate SimpleMongoReader into QueryEngine
    - apps/simple/mongo.ts

##Feature
- add basic MongoDB support

##To-do list:

- [X] Test logic locally
- [X] Check package runs locally
- [X] Write demo
- [X] Ask for merge

### CODE REVIEW

**Comment by kkang2097** [comment]
Okay I think it's worth looking at by now

**Comment by yisding** [comment]
Thanks Elliot! 2 small notes: 1. can you run prettier on the code? I should have it set up to do on commit, but not sure why it doesn't run all the time. Need to look into that. 2. I'm not sure .limit(Infinity) is officially supported by the API: https://stackoverflow.com/questions/43788801/does-mongodb-support-passing-infinity-into-limit 0 looks like it does what you want by default.

**Comment by kkang2097** [comment]
Yup

**Review by yisding — APPROVED** [review]
Looks good. Thank you!

**Pull request merged**
