### PR TITLE
Add Braintrust as an evaluations and testing tool for create-llama

### PR DESCRIPTION
**Pull request by davidatbraintrust**
Hi,

We added braintrust as a testing script for the javascript templates. Let us know if this is helpful and we can help get this merged in.

Thank you!
David

### CODE REVIEW

**Comment by yisding** [comment]
Thanks for the contribution. This looks cool!

I'd like this to be an option. @marcusschiesser can you help take a look at this and help figure out what we need to do to support different vector DB and eval options?

**Comment by marcusschiesser** [comment]
@davidatbraintrust, Thanks for your PR! To make your feature optional, you're best doing the following:

1. Create a new `evals/braintrust` folder in https://github.com/run-llama/LlamaIndexTS/tree/main/packages/create-llama/templates/components and put your typescript code there (sorry, no support for components yet for Python code).
2. In your test code, check if `BRAINTRUST_API_KEY` is set; if not, throw an error (then you don't need to generate a `.env` file)
2. Add `export type TemplateEvals = "none" | "braintrust";` to https://github.com/run-llama/LlamaIndexTS/blob/main/packages/create-llama/templates/types.ts
3. Ask the user for the `TemplateEvals` selection before the OpenAI key, see https://github.com/run-llama/LlamaIndexTS/blob/main/packages/create-llama/index.ts#L307 
4. Create a function to copy the eval component that the user selected (code similar to this one: https://github.com/run-llama/LlamaIndexTS/blob/main/packages/create-llama/templates/index.ts#L128-L139)
5. Modify the package JSON (see https://github.com/run-llama/LlamaIndexTS/blob/main/packages/create-llama/templates/index.ts#L189-L199)

Please wrap your code in dedicated functions (e.g. use `copyEval`) instead of inlining your code. If you need any help, let me know!

**Comment by davidatbraintrust** [comment]
This is very helpful! We'll work to make these changes and get back to you here. Thank you!

**Review by himself65 — COMMENTED** [review]
Template lock files are unnecessary since they will be copied to the user side. And they might user pnpm/yarn

**Comment by EmanuelCampos** [comment]
bump @davidatbraintrust

**Comment by marcusschiesser** [comment]
Please send PR to the new repo: https://github.com/run-llama/create-llama again - Sorry for the trouble and let me know if you need any help

**Pull request closed without merging**
