### PR TITLE
fix(perf): use regex to spilt texts

### PR DESCRIPTION
**Pull request by himself65**
Fixes: https://github.com/run-llama/LlamaIndexTS/issues/363

### CODE REVIEW

**Comment by preemoDez** [comment]
Thanks! That was super fast! I really appreciate that.

**Comment by preemoDez** [comment]
@yisding Could you please publish a new release with this fix?

**Comment by preemoDez** [comment]
I'm sorry, I noticed that mostly @marcusschiesser deals with publishing new releases. It is very important, and I would really appreciate it if I could start using the updated Llama Index ASAP.

**Comment by himself65** [comment]
> I'm sorry, I noticed that mostly @marcusschiesser deals with publishing new releases. It is very important, and I would really appreciate it if I could start using the updated Llama Index ASAP.
> 
> 

we will publish soon but if you cannot wait it. You can learn to patch-package

https://www.npmjs.com/package/patch-package

**Pull request merged**
